image:
  file: .gitpod.Dockerfile
tasks:
  - name: Run project
    command: flutter run -d web-server --web-port 3000

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
